In [23]:
#1. Create a NumPy array from 10 to 100 with step 10

import numpy as np

a = np.arange(10, 101, 10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [24]:
#2. Create a 3 × 4 array of zeros

import numpy as np

a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
#3. Print ndim, shape, size and dtype

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print("Dimensions:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data type:", a.dtype)

Dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64


In [25]:
#4. Extract the last element from a 1D array

import numpy as np

a = np.array([10, 20, 30, 40, 50])

print(a[-1])

50


In [27]:
#5. Select the first two columns of a 2D array

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [ ]:
#6. Reshape 12 numbers into a 3 × 4 matrix

import numpy as np

a = np.arange(1, 13)

b = a.reshape(3, 4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#7. Transpose a 2 × 3 matrix

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
#8. Multiply every element by 5

import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a * 5)

[ 5 10 15 20 25]


In [29]:
#9. Create feature matrix X with 5 samples and 3 features

import numpy as np

X = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90],
              [20, 30, 40],
              [50, 60, 70]])

print(X)
print("Shape:", X.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [20 30 40]
 [50 60 70]]
Shape: (5, 3)


In [ ]:
#10. Calculate mean of each feature using axis=0


import numpy as np

X = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(np.mean(X, axis=0))

[40. 50. 60.]


In [32]:
#11. Filter rows where first feature is greater than 50

import numpy as np

X = np.array([[20, 30, 40],
              [60, 70, 80],
              [90, 50, 30],
              [40, 80, 20]])

result = X[X[:, 0] > 50]

print(result)

[[60 70 80]
 [90 50 30]]


In [33]:
#12. Standardize every feature column

import numpy as np

X = np.array([[10, 20],
              [20, 40],
              [30, 60]], dtype=float)

standardized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

print(standardized)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [34]:
#13. Create a random matrix of shape (10, 4) with fixed seed

import numpy as np

np.random.seed(10)

a = np.random.rand(10, 4)
print(a)

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]
 [0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698 0.51313824]
 [0.65039718 0.60103895 0.8052232  0.52164715]
 [0.90864888 0.31923609 0.09045935 0.30070006]
 [0.11398436 0.82868133 0.04689632 0.62628715]]


In [36]:
#14. Calculate X @ weights

import numpy as np

X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

weights = np.array([2, 3])

result = X @ weights

print(result)

[ 8 18 28]


In [37]:
#15. Add a bias vector using broadcasting


import numpy as np

X = np.array([[10, 20, 30],
              [40, 50, 60]])

bias = np.array([1, 2, 3])

result = X + bias

print(result)

[[11 22 33]
 [41 52 63]]


In [ ]:
#16. Calculate MSE between y_true and y_pred

import numpy as np

y_true = np.array([10, 20, 30, 40])
y_pred = np.array([12, 18, 28, 42])

mse = np.mean((y_true - y_pred) ** 2)

print("MSE:", mse)

MSE: 4.0


In [38]:
#17. Create a 28 × 28 grayscale image

import numpy as np

image = np.zeros((28, 28))

print("Shape:", image.shape)

Shape: (28, 28)


In [39]:
#18. Create a batch of 64 RGB images of size 224 × 224

import numpy as np

images = np.zeros((64, 224, 224, 3))

print("Shape:", images.shape)

Shape: (64, 224, 224, 3)


In [40]:
#19. Create an array containing NaN and calculate NaN-safe mean

import numpy as np

a = np.array([10, 20, np.nan, 40, 50])

mean = np.nanmean(a)

print("Mean:", mean)

Mean: 30.0


In [41]:
#20. Difference between A * B and A @ B

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("A * B:")
print(A * B)

print("A @ B:")
print(A @ B)

A * B:
[[ 5 12]
 [21 32]]
A @ B:
[[19 22]
 [43 50]]


In [42]:
#Normalization and Standardization


import numpy as np

data = np.array([10, 20, 30, 40, 50], dtype=float)

normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
standardized = (data - np.mean(data)) / np.std(data)

print("Original:", data)
print("Normalized:", normalized)
print("Standardized:", standardized)
print("Standardized mean:", np.mean(standardized))
print("Standardized std:", np.std(standardized))

Original: [10. 20. 30. 40. 50.]
Normalized: [0.   0.25 0.5  0.75 1.  ]
Standardized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Standardized mean: 0.0
Standardized std: 0.9999999999999999
